# Concatenate multiple plsql scripts together into one script. Files are read in
# order by name, so this works best if you're using numbered scripts e.g.
#
# 0001_create_customer_tables.sql
# 0002_create_order_tables.sql

$ErrorActionPreference = 'Stop'

$files = Get-ChildItem C:\myapp\sql\up | Sort-Object

$outputFile = "C:\myapp\sql\merged.sql"

cls;

# Oracle specific: SQL*Plus error handling
"-- This SQL file has been generated by a script." | Out-File -FilePath $outputFile -Append
"whenever sqlerror exit sql.sqlcode rollback;" | Out-File -FilePath $outputFile
"set serveroutput on;" | Out-File -FilePath $outputFile -Append

foreach ($file in $files) {
	Write-Output "$file";

	$lines = Get-Content $file.FullName;

	"--------------------------------------------------------------------------------" | Out-File -FilePath $outputFile -Append
	"execute dbms_output.put_line('$file')" | Out-File -FilePath $outputFile -Append
	"--------------------------------------------------------------------------------" | Out-File -FilePath $outputFile -Append
	$lines | Out-File -FilePath $outputFile -Append -Encoding "OEM"
}

# Oracle specific: exit SQL*Plus
"exit" | Out-File -FilePath $outputFile -Append -Encoding "OEM"